name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports: [6379:6379]

    steps:
      # ---------- FRONT-END ----------
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install front-end deps
        run: |
          cd frontend
          corepack enable
          pnpm install --frozen-lockfile

      - name: Run Vitest
        run: |
          cd frontend
          pnpm test

      # ---------- BACK-END ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Pytest
        run: |
          pytest -q backend/tests